# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: Default
variables:
  rgname: 'yamlrg'
  loc: "east us"

steps:
- task: AzurePowerShell@5
  displayName: Az powershell
  inputs:
    azureSubscription: 'azure connection'
    ScriptType: 'InlineScript'
    Inline: |
      # You can write your azure powershell scripts inline here. 
      # You can also pass predefined and custom variables to this script using arguments
      
      new-azresourcegroup -name $(rgname) -location $(loc)
    azurePowerShellVersion: 'LatestVersion'
